package com.lycenway.chr.backbone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BinghaiProof service. Represents a row in the &quot;base_binghai_proof&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lycenway.chr.backbone.model.impl.BinghaiProofModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lycenway.chr.backbone.model.impl.BinghaiProofImpl}.
 * </p>
 *
 * @author lycenway
 * @see BinghaiProof
 * @see com.lycenway.chr.backbone.model.impl.BinghaiProofImpl
 * @see com.lycenway.chr.backbone.model.impl.BinghaiProofModelImpl
 * @generated
 */
public interface BinghaiProofModel extends BaseModel<BinghaiProof>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Binghai Attachments Pictures model instance should use the {@link BinghaiProof} interface instead.
     */

    /**
     * Returns the primary key of this Binghai Attachments Pictures.
     *
     * @return the primary key of this Binghai Attachments Pictures
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this Binghai Attachments Pictures.
     *
     * @param primaryKey the primary key of this Binghai Attachments Pictures
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the mime of this Binghai Attachments Pictures.
     *
     * @return the mime of this Binghai Attachments Pictures
     */
    @AutoEscape
    public String getMime();

    /**
     * Sets the mime of this Binghai Attachments Pictures.
     *
     * @param mime the mime of this Binghai Attachments Pictures
     */
    public void setMime(String mime);

    /**
     * Returns the url of this Binghai Attachments Pictures.
     *
     * @return the url of this Binghai Attachments Pictures
     */
    @AutoEscape
    public String getUrl();

    /**
     * Sets the url of this Binghai Attachments Pictures.
     *
     * @param url the url of this Binghai Attachments Pictures
     */
    public void setUrl(String url);

    /**
     * Returns the binghai ID of this Binghai Attachments Pictures.
     *
     * @return the binghai ID of this Binghai Attachments Pictures
     */
    @AutoEscape
    public String getBinghaiId();

    /**
     * Sets the binghai ID of this Binghai Attachments Pictures.
     *
     * @param binghaiId the binghai ID of this Binghai Attachments Pictures
     */
    public void setBinghaiId(String binghaiId);

    /**
     * Returns the binghai proof ID of this Binghai Attachments Pictures.
     *
     * @return the binghai proof ID of this Binghai Attachments Pictures
     */
    public long getBinghaiProofId();

    /**
     * Sets the binghai proof ID of this Binghai Attachments Pictures.
     *
     * @param binghaiProofId the binghai proof ID of this Binghai Attachments Pictures
     */
    public void setBinghaiProofId(long binghaiProofId);

    /**
     * Returns the group ID of this Binghai Attachments Pictures.
     *
     * @return the group ID of this Binghai Attachments Pictures
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this Binghai Attachments Pictures.
     *
     * @param groupId the group ID of this Binghai Attachments Pictures
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this Binghai Attachments Pictures.
     *
     * @return the company ID of this Binghai Attachments Pictures
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this Binghai Attachments Pictures.
     *
     * @param companyId the company ID of this Binghai Attachments Pictures
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this Binghai Attachments Pictures.
     *
     * @return the user ID of this Binghai Attachments Pictures
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this Binghai Attachments Pictures.
     *
     * @param userId the user ID of this Binghai Attachments Pictures
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this Binghai Attachments Pictures.
     *
     * @return the user uuid of this Binghai Attachments Pictures
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this Binghai Attachments Pictures.
     *
     * @param userUuid the user uuid of this Binghai Attachments Pictures
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this Binghai Attachments Pictures.
     *
     * @return the user name of this Binghai Attachments Pictures
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this Binghai Attachments Pictures.
     *
     * @param userName the user name of this Binghai Attachments Pictures
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this Binghai Attachments Pictures.
     *
     * @return the create date of this Binghai Attachments Pictures
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this Binghai Attachments Pictures.
     *
     * @param createDate the create date of this Binghai Attachments Pictures
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this Binghai Attachments Pictures.
     *
     * @return the modified date of this Binghai Attachments Pictures
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this Binghai Attachments Pictures.
     *
     * @param modifiedDate the modified date of this Binghai Attachments Pictures
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.lycenway.chr.backbone.model.BinghaiProof binghaiProof);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.lycenway.chr.backbone.model.BinghaiProof> toCacheModel();

    @Override
    public com.lycenway.chr.backbone.model.BinghaiProof toEscapedModel();

    @Override
    public com.lycenway.chr.backbone.model.BinghaiProof toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
