package com.lycenway.chr.backbone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BinghaiPingfen service. Represents a row in the &quot;lov_binghai_pingfen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lycenway.chr.backbone.model.impl.BinghaiPingfenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lycenway.chr.backbone.model.impl.BinghaiPingfenImpl}.
 * </p>
 *
 * @author lycenway
 * @see BinghaiPingfen
 * @see com.lycenway.chr.backbone.model.impl.BinghaiPingfenImpl
 * @see com.lycenway.chr.backbone.model.impl.BinghaiPingfenModelImpl
 * @generated
 */
public interface BinghaiPingfenModel extends BaseModel<BinghaiPingfen>,
    GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a binghai pingfen model instance should use the {@link BinghaiPingfen} interface instead.
     */

    /**
     * Returns the primary key of this binghai pingfen.
     *
     * @return the primary key of this binghai pingfen
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this binghai pingfen.
     *
     * @param primaryKey the primary key of this binghai pingfen
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the binghai pingfen ID of this binghai pingfen.
     *
     * @return the binghai pingfen ID of this binghai pingfen
     */
    public long getBinghaiPingfenId();

    /**
     * Sets the binghai pingfen ID of this binghai pingfen.
     *
     * @param binghaiPingfenId the binghai pingfen ID of this binghai pingfen
     */
    public void setBinghaiPingfenId(long binghaiPingfenId);

    /**
     * Returns the group ID of this binghai pingfen.
     *
     * @return the group ID of this binghai pingfen
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this binghai pingfen.
     *
     * @param groupId the group ID of this binghai pingfen
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this binghai pingfen.
     *
     * @return the company ID of this binghai pingfen
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this binghai pingfen.
     *
     * @param companyId the company ID of this binghai pingfen
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this binghai pingfen.
     *
     * @return the user ID of this binghai pingfen
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this binghai pingfen.
     *
     * @param userId the user ID of this binghai pingfen
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this binghai pingfen.
     *
     * @return the user uuid of this binghai pingfen
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this binghai pingfen.
     *
     * @param userUuid the user uuid of this binghai pingfen
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this binghai pingfen.
     *
     * @return the user name of this binghai pingfen
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this binghai pingfen.
     *
     * @param userName the user name of this binghai pingfen
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this binghai pingfen.
     *
     * @return the create date of this binghai pingfen
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this binghai pingfen.
     *
     * @param createDate the create date of this binghai pingfen
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this binghai pingfen.
     *
     * @return the modified date of this binghai pingfen
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this binghai pingfen.
     *
     * @param modifiedDate the modified date of this binghai pingfen
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the dalei of this binghai pingfen.
     *
     * @return the dalei of this binghai pingfen
     */
    @AutoEscape
    public String getDalei();

    /**
     * Sets the dalei of this binghai pingfen.
     *
     * @param dalei the dalei of this binghai pingfen
     */
    public void setDalei(String dalei);

    /**
     * Returns the vmin of this binghai pingfen.
     *
     * @return the vmin of this binghai pingfen
     */
    public double getVmin();

    /**
     * Sets the vmin of this binghai pingfen.
     *
     * @param vmin the vmin of this binghai pingfen
     */
    public void setVmin(double vmin);

    /**
     * Returns the vmax of this binghai pingfen.
     *
     * @return the vmax of this binghai pingfen
     */
    public double getVmax();

    /**
     * Sets the vmax of this binghai pingfen.
     *
     * @param vmax the vmax of this binghai pingfen
     */
    public void setVmax(double vmax);

    /**
     * Returns the xiangmu of this binghai pingfen.
     *
     * @return the xiangmu of this binghai pingfen
     */
    @AutoEscape
    public String getXiangmu();

    /**
     * Sets the xiangmu of this binghai pingfen.
     *
     * @param xiangmu the xiangmu of this binghai pingfen
     */
    public void setXiangmu(String xiangmu);

    /**
     * Returns the dengji of this binghai pingfen.
     *
     * @return the dengji of this binghai pingfen
     */
    @AutoEscape
    public String getDengji();

    /**
     * Sets the dengji of this binghai pingfen.
     *
     * @param dengji the dengji of this binghai pingfen
     */
    public void setDengji(String dengji);

    /**
     * Returns the dengji_min of this binghai pingfen.
     *
     * @return the dengji_min of this binghai pingfen
     */
    public double getDengji_min();

    /**
     * Sets the dengji_min of this binghai pingfen.
     *
     * @param dengji_min the dengji_min of this binghai pingfen
     */
    public void setDengji_min(double dengji_min);

    /**
     * Returns the dengji_max of this binghai pingfen.
     *
     * @return the dengji_max of this binghai pingfen
     */
    public double getDengji_max();

    /**
     * Sets the dengji_max of this binghai pingfen.
     *
     * @param dengji_max the dengji_max of this binghai pingfen
     */
    public void setDengji_max(double dengji_max);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.lycenway.chr.backbone.model.BinghaiPingfen binghaiPingfen);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.lycenway.chr.backbone.model.BinghaiPingfen> toCacheModel();

    @Override
    public com.lycenway.chr.backbone.model.BinghaiPingfen toEscapedModel();

    @Override
    public com.lycenway.chr.backbone.model.BinghaiPingfen toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
