package com.lycenway.chr.backbone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Binghai service. Represents a row in the &quot;base_binghai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lycenway.chr.backbone.model.impl.BinghaiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lycenway.chr.backbone.model.impl.BinghaiImpl}.
 * </p>
 *
 * @author lycenway
 * @see Binghai
 * @see com.lycenway.chr.backbone.model.impl.BinghaiImpl
 * @see com.lycenway.chr.backbone.model.impl.BinghaiModelImpl
 * @generated
 */
public interface BinghaiModel extends BaseModel<Binghai>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Binghai Case Weixiu Wenti model instance should use the {@link Binghai} interface instead.
     */

    /**
     * Returns the primary key of this Binghai Case Weixiu Wenti.
     *
     * @return the primary key of this Binghai Case Weixiu Wenti
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this Binghai Case Weixiu Wenti.
     *
     * @param primaryKey the primary key of this Binghai Case Weixiu Wenti
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the hkey of this Binghai Case Weixiu Wenti.
     *
     * @return the hkey of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getHkey();

    /**
     * Sets the hkey of this Binghai Case Weixiu Wenti.
     *
     * @param hkey the hkey of this Binghai Case Weixiu Wenti
     */
    public void setHkey(String hkey);

    /**
     * Returns the mu title of this Binghai Case Weixiu Wenti.
     *
     * @return the mu title of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getMuTitle();

    /**
     * Sets the mu title of this Binghai Case Weixiu Wenti.
     *
     * @param muTitle the mu title of this Binghai Case Weixiu Wenti
     */
    public void setMuTitle(String muTitle);

    /**
     * Returns the buwei of this Binghai Case Weixiu Wenti.
     *
     * @return the buwei of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getBuwei();

    /**
     * Sets the buwei of this Binghai Case Weixiu Wenti.
     *
     * @param buwei the buwei of this Binghai Case Weixiu Wenti
     */
    public void setBuwei(String buwei);

    /**
     * Returns the tab of this Binghai Case Weixiu Wenti.
     *
     * @return the tab of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getTab();

    /**
     * Sets the tab of this Binghai Case Weixiu Wenti.
     *
     * @param tab the tab of this Binghai Case Weixiu Wenti
     */
    public void setTab(String tab);

    /**
     * Returns the c name of this Binghai Case Weixiu Wenti.
     *
     * @return the c name of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getCName();

    /**
     * Sets the c name of this Binghai Case Weixiu Wenti.
     *
     * @param cName the c name of this Binghai Case Weixiu Wenti
     */
    public void setCName(String cName);

    /**
     * Returns the c ID of this Binghai Case Weixiu Wenti.
     *
     * @return the c ID of this Binghai Case Weixiu Wenti
     */
    public int getCId();

    /**
     * Sets the c ID of this Binghai Case Weixiu Wenti.
     *
     * @param cId the c ID of this Binghai Case Weixiu Wenti
     */
    public void setCId(int cId);

    /**
     * Returns the c1 name of this Binghai Case Weixiu Wenti.
     *
     * @return the c1 name of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getC1Name();

    /**
     * Sets the c1 name of this Binghai Case Weixiu Wenti.
     *
     * @param c1Name the c1 name of this Binghai Case Weixiu Wenti
     */
    public void setC1Name(String c1Name);

    /**
     * Returns the c1 ID of this Binghai Case Weixiu Wenti.
     *
     * @return the c1 ID of this Binghai Case Weixiu Wenti
     */
    public int getC1Id();

    /**
     * Sets the c1 ID of this Binghai Case Weixiu Wenti.
     *
     * @param c1Id the c1 ID of this Binghai Case Weixiu Wenti
     */
    public void setC1Id(int c1Id);

    /**
     * Returns the c2 name of this Binghai Case Weixiu Wenti.
     *
     * @return the c2 name of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getC2Name();

    /**
     * Sets the c2 name of this Binghai Case Weixiu Wenti.
     *
     * @param c2Name the c2 name of this Binghai Case Weixiu Wenti
     */
    public void setC2Name(String c2Name);

    /**
     * Returns the c2 ID of this Binghai Case Weixiu Wenti.
     *
     * @return the c2 ID of this Binghai Case Weixiu Wenti
     */
    public int getC2Id();

    /**
     * Sets the c2 ID of this Binghai Case Weixiu Wenti.
     *
     * @param c2Id the c2 ID of this Binghai Case Weixiu Wenti
     */
    public void setC2Id(int c2Id);

    /**
     * Returns the binghai leixing of this Binghai Case Weixiu Wenti.
     *
     * @return the binghai leixing of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getBinghaiLeixing();

    /**
     * Sets the binghai leixing of this Binghai Case Weixiu Wenti.
     *
     * @param binghaiLeixing the binghai leixing of this Binghai Case Weixiu Wenti
     */
    public void setBinghaiLeixing(String binghaiLeixing);

    /**
     * Returns the stage name of this Binghai Case Weixiu Wenti.
     *
     * @return the stage name of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getStageName();

    /**
     * Sets the stage name of this Binghai Case Weixiu Wenti.
     *
     * @param stageName the stage name of this Binghai Case Weixiu Wenti
     */
    public void setStageName(String stageName);

    /**
     * Returns the stage ID of this Binghai Case Weixiu Wenti.
     *
     * @return the stage ID of this Binghai Case Weixiu Wenti
     */
    public int getStageId();

    /**
     * Sets the stage ID of this Binghai Case Weixiu Wenti.
     *
     * @param stageId the stage ID of this Binghai Case Weixiu Wenti
     */
    public void setStageId(int stageId);

    /**
     * Returns the koufen of this Binghai Case Weixiu Wenti.
     *
     * @return the koufen of this Binghai Case Weixiu Wenti
     */
    public int getKoufen();

    /**
     * Sets the koufen of this Binghai Case Weixiu Wenti.
     *
     * @param koufen the koufen of this Binghai Case Weixiu Wenti
     */
    public void setKoufen(int koufen);

    /**
     * Returns the visit content of this Binghai Case Weixiu Wenti.
     *
     * @return the visit content of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getVisitContent();

    /**
     * Sets the visit content of this Binghai Case Weixiu Wenti.
     *
     * @param visitContent the visit content of this Binghai Case Weixiu Wenti
     */
    public void setVisitContent(String visitContent);

    /**
     * Returns the visited by of this Binghai Case Weixiu Wenti.
     *
     * @return the visited by of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getVisitedBy();

    /**
     * Sets the visited by of this Binghai Case Weixiu Wenti.
     *
     * @param visitedBy the visited by of this Binghai Case Weixiu Wenti
     */
    public void setVisitedBy(String visitedBy);

    /**
     * Returns the visited on of this Binghai Case Weixiu Wenti.
     *
     * @return the visited on of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getVisitedOn();

    /**
     * Sets the visited on of this Binghai Case Weixiu Wenti.
     *
     * @param visitedOn the visited on of this Binghai Case Weixiu Wenti
     */
    public void setVisitedOn(String visitedOn);

    /**
     * Returns the revisited by of this Binghai Case Weixiu Wenti.
     *
     * @return the revisited by of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getRevisitedBy();

    /**
     * Sets the revisited by of this Binghai Case Weixiu Wenti.
     *
     * @param revisitedBy the revisited by of this Binghai Case Weixiu Wenti
     */
    public void setRevisitedBy(String revisitedBy);

    /**
     * Returns the revisited on of this Binghai Case Weixiu Wenti.
     *
     * @return the revisited on of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getRevisitedOn();

    /**
     * Sets the revisited on of this Binghai Case Weixiu Wenti.
     *
     * @param revisitedOn the revisited on of this Binghai Case Weixiu Wenti
     */
    public void setRevisitedOn(String revisitedOn);

    /**
     * Returns the binghai shuzhi of this Binghai Case Weixiu Wenti.
     *
     * @return the binghai shuzhi of this Binghai Case Weixiu Wenti
     */
    public int getBinghaiShuzhi();

    /**
     * Sets the binghai shuzhi of this Binghai Case Weixiu Wenti.
     *
     * @param binghaiShuzhi the binghai shuzhi of this Binghai Case Weixiu Wenti
     */
    public void setBinghaiShuzhi(int binghaiShuzhi);

    /**
     * Returns the gongzuoliang action of this Binghai Case Weixiu Wenti.
     *
     * @return the gongzuoliang action of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getGongzuoliangAction();

    /**
     * Sets the gongzuoliang action of this Binghai Case Weixiu Wenti.
     *
     * @param gongzuoliangAction the gongzuoliang action of this Binghai Case Weixiu Wenti
     */
    public void setGongzuoliangAction(String gongzuoliangAction);

    /**
     * Returns the gongzuoliang name of this Binghai Case Weixiu Wenti.
     *
     * @return the gongzuoliang name of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getGongzuoliangName();

    /**
     * Sets the gongzuoliang name of this Binghai Case Weixiu Wenti.
     *
     * @param gongzuoliangName the gongzuoliang name of this Binghai Case Weixiu Wenti
     */
    public void setGongzuoliangName(String gongzuoliangName);

    /**
     * Returns the gongzuoliang unit of this Binghai Case Weixiu Wenti.
     *
     * @return the gongzuoliang unit of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getGongzuoliangUnit();

    /**
     * Sets the gongzuoliang unit of this Binghai Case Weixiu Wenti.
     *
     * @param gongzuoliangUnit the gongzuoliang unit of this Binghai Case Weixiu Wenti
     */
    public void setGongzuoliangUnit(String gongzuoliangUnit);

    /**
     * Returns the gongzuoliang tval of this Binghai Case Weixiu Wenti.
     *
     * @return the gongzuoliang tval of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getGongzuoliangTval();

    /**
     * Sets the gongzuoliang tval of this Binghai Case Weixiu Wenti.
     *
     * @param gongzuoliangTval the gongzuoliang tval of this Binghai Case Weixiu Wenti
     */
    public void setGongzuoliangTval(String gongzuoliangTval);

    /**
     * Returns the binghai ID of this Binghai Case Weixiu Wenti.
     *
     * @return the binghai ID of this Binghai Case Weixiu Wenti
     */
    public long getBinghaiId();

    /**
     * Sets the binghai ID of this Binghai Case Weixiu Wenti.
     *
     * @param binghaiId the binghai ID of this Binghai Case Weixiu Wenti
     */
    public void setBinghaiId(long binghaiId);

    /**
     * Returns the group ID of this Binghai Case Weixiu Wenti.
     *
     * @return the group ID of this Binghai Case Weixiu Wenti
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this Binghai Case Weixiu Wenti.
     *
     * @param groupId the group ID of this Binghai Case Weixiu Wenti
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this Binghai Case Weixiu Wenti.
     *
     * @return the company ID of this Binghai Case Weixiu Wenti
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this Binghai Case Weixiu Wenti.
     *
     * @param companyId the company ID of this Binghai Case Weixiu Wenti
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this Binghai Case Weixiu Wenti.
     *
     * @return the user ID of this Binghai Case Weixiu Wenti
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this Binghai Case Weixiu Wenti.
     *
     * @param userId the user ID of this Binghai Case Weixiu Wenti
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this Binghai Case Weixiu Wenti.
     *
     * @return the user uuid of this Binghai Case Weixiu Wenti
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this Binghai Case Weixiu Wenti.
     *
     * @param userUuid the user uuid of this Binghai Case Weixiu Wenti
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this Binghai Case Weixiu Wenti.
     *
     * @return the user name of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this Binghai Case Weixiu Wenti.
     *
     * @param userName the user name of this Binghai Case Weixiu Wenti
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this Binghai Case Weixiu Wenti.
     *
     * @return the create date of this Binghai Case Weixiu Wenti
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this Binghai Case Weixiu Wenti.
     *
     * @param createDate the create date of this Binghai Case Weixiu Wenti
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this Binghai Case Weixiu Wenti.
     *
     * @return the modified date of this Binghai Case Weixiu Wenti
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this Binghai Case Weixiu Wenti.
     *
     * @param modifiedDate the modified date of this Binghai Case Weixiu Wenti
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the proof count of this Binghai Case Weixiu Wenti.
     *
     * @return the proof count of this Binghai Case Weixiu Wenti
     */
    public long getProofCount();

    /**
     * Sets the proof count of this Binghai Case Weixiu Wenti.
     *
     * @param proofCount the proof count of this Binghai Case Weixiu Wenti
     */
    public void setProofCount(long proofCount);

    /**
     * Returns the reference radio of this Binghai Case Weixiu Wenti.
     *
     * @return the reference radio of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getReferenceRadio();

    /**
     * Sets the reference radio of this Binghai Case Weixiu Wenti.
     *
     * @param referenceRadio the reference radio of this Binghai Case Weixiu Wenti
     */
    public void setReferenceRadio(String referenceRadio);

    /**
     * Returns the daocha json of this Binghai Case Weixiu Wenti.
     *
     * @return the daocha json of this Binghai Case Weixiu Wenti
     */
    @AutoEscape
    public String getDaochaJson();

    /**
     * Sets the daocha json of this Binghai Case Weixiu Wenti.
     *
     * @param daochaJson the daocha json of this Binghai Case Weixiu Wenti
     */
    public void setDaochaJson(String daochaJson);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.lycenway.chr.backbone.model.Binghai binghai);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.lycenway.chr.backbone.model.Binghai> toCacheModel();

    @Override
    public com.lycenway.chr.backbone.model.Binghai toEscapedModel();

    @Override
    public com.lycenway.chr.backbone.model.Binghai toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
