package com.lycenway.chr.backbone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LOVMuType service. Represents a row in the &quot;lov_mu_type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lycenway.chr.backbone.model.impl.LOVMuTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lycenway.chr.backbone.model.impl.LOVMuTypeImpl}.
 * </p>
 *
 * @author lycenway
 * @see LOVMuType
 * @see com.lycenway.chr.backbone.model.impl.LOVMuTypeImpl
 * @see com.lycenway.chr.backbone.model.impl.LOVMuTypeModelImpl
 * @generated
 */
public interface LOVMuTypeModel extends BaseModel<LOVMuType> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Lisf of Value Mgmt Unit Type model instance should use the {@link LOVMuType} interface instead.
     */

    /**
     * Returns the primary key of this Lisf of Value Mgmt Unit Type.
     *
     * @return the primary key of this Lisf of Value Mgmt Unit Type
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this Lisf of Value Mgmt Unit Type.
     *
     * @param primaryKey the primary key of this Lisf of Value Mgmt Unit Type
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the code of this Lisf of Value Mgmt Unit Type.
     *
     * @return the code of this Lisf of Value Mgmt Unit Type
     */
    @AutoEscape
    public String getCode();

    /**
     * Sets the code of this Lisf of Value Mgmt Unit Type.
     *
     * @param code the code of this Lisf of Value Mgmt Unit Type
     */
    public void setCode(String code);

    /**
     * Returns the title of this Lisf of Value Mgmt Unit Type.
     *
     * @return the title of this Lisf of Value Mgmt Unit Type
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this Lisf of Value Mgmt Unit Type.
     *
     * @param title the title of this Lisf of Value Mgmt Unit Type
     */
    public void setTitle(String title);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.lycenway.chr.backbone.model.LOVMuType lovMuType);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.lycenway.chr.backbone.model.LOVMuType> toCacheModel();

    @Override
    public com.lycenway.chr.backbone.model.LOVMuType toEscapedModel();

    @Override
    public com.lycenway.chr.backbone.model.LOVMuType toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
