package com.lycenway.chr.backbone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MuInterrel service. Represents a row in the &quot;base_mu_interrel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lycenway.chr.backbone.model.impl.MuInterrelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lycenway.chr.backbone.model.impl.MuInterrelImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuInterrel
 * @see com.lycenway.chr.backbone.model.impl.MuInterrelImpl
 * @see com.lycenway.chr.backbone.model.impl.MuInterrelModelImpl
 * @generated
 */
public interface MuInterrelModel extends BaseModel<MuInterrel>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Mgmt Unit Inter Relationship model instance should use the {@link MuInterrel} interface instead.
     */

    /**
     * Returns the primary key of this Mgmt Unit Inter Relationship.
     *
     * @return the primary key of this Mgmt Unit Inter Relationship
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this Mgmt Unit Inter Relationship.
     *
     * @param primaryKey the primary key of this Mgmt Unit Inter Relationship
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the hkey of this Mgmt Unit Inter Relationship.
     *
     * @return the hkey of this Mgmt Unit Inter Relationship
     */
    @AutoEscape
    public String getHkey();

    /**
     * Sets the hkey of this Mgmt Unit Inter Relationship.
     *
     * @param hkey the hkey of this Mgmt Unit Inter Relationship
     */
    public void setHkey(String hkey);

    /**
     * Returns the par of this Mgmt Unit Inter Relationship.
     *
     * @return the par of this Mgmt Unit Inter Relationship
     */
    @AutoEscape
    public String getPar();

    /**
     * Sets the par of this Mgmt Unit Inter Relationship.
     *
     * @param par the par of this Mgmt Unit Inter Relationship
     */
    public void setPar(String par);

    /**
     * Returns the type of this Mgmt Unit Inter Relationship.
     *
     * @return the type of this Mgmt Unit Inter Relationship
     */
    @AutoEscape
    public String getType();

    /**
     * Sets the type of this Mgmt Unit Inter Relationship.
     *
     * @param type the type of this Mgmt Unit Inter Relationship
     */
    public void setType(String type);

    /**
     * Returns the mu interrel ID of this Mgmt Unit Inter Relationship.
     *
     * @return the mu interrel ID of this Mgmt Unit Inter Relationship
     */
    public long getMuInterrelId();

    /**
     * Sets the mu interrel ID of this Mgmt Unit Inter Relationship.
     *
     * @param muInterrelId the mu interrel ID of this Mgmt Unit Inter Relationship
     */
    public void setMuInterrelId(long muInterrelId);

    /**
     * Returns the group ID of this Mgmt Unit Inter Relationship.
     *
     * @return the group ID of this Mgmt Unit Inter Relationship
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this Mgmt Unit Inter Relationship.
     *
     * @param groupId the group ID of this Mgmt Unit Inter Relationship
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this Mgmt Unit Inter Relationship.
     *
     * @return the company ID of this Mgmt Unit Inter Relationship
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this Mgmt Unit Inter Relationship.
     *
     * @param companyId the company ID of this Mgmt Unit Inter Relationship
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this Mgmt Unit Inter Relationship.
     *
     * @return the user ID of this Mgmt Unit Inter Relationship
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this Mgmt Unit Inter Relationship.
     *
     * @param userId the user ID of this Mgmt Unit Inter Relationship
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this Mgmt Unit Inter Relationship.
     *
     * @return the user uuid of this Mgmt Unit Inter Relationship
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this Mgmt Unit Inter Relationship.
     *
     * @param userUuid the user uuid of this Mgmt Unit Inter Relationship
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this Mgmt Unit Inter Relationship.
     *
     * @return the user name of this Mgmt Unit Inter Relationship
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this Mgmt Unit Inter Relationship.
     *
     * @param userName the user name of this Mgmt Unit Inter Relationship
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this Mgmt Unit Inter Relationship.
     *
     * @return the create date of this Mgmt Unit Inter Relationship
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this Mgmt Unit Inter Relationship.
     *
     * @param createDate the create date of this Mgmt Unit Inter Relationship
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this Mgmt Unit Inter Relationship.
     *
     * @return the modified date of this Mgmt Unit Inter Relationship
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this Mgmt Unit Inter Relationship.
     *
     * @param modifiedDate the modified date of this Mgmt Unit Inter Relationship
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.lycenway.chr.backbone.model.MuInterrel muInterrel);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.lycenway.chr.backbone.model.MuInterrel> toCacheModel();

    @Override
    public com.lycenway.chr.backbone.model.MuInterrel toEscapedModel();

    @Override
    public com.lycenway.chr.backbone.model.MuInterrel toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
