package com.lycenway.chr.backbone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.lycenway.chr.backbone.service.persistence.MuPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Mu service. Represents a row in the &quot;base_mu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lycenway.chr.backbone.model.impl.MuModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lycenway.chr.backbone.model.impl.MuImpl}.
 * </p>
 *
 * @author lycenway
 * @see Mu
 * @see com.lycenway.chr.backbone.model.impl.MuImpl
 * @see com.lycenway.chr.backbone.model.impl.MuModelImpl
 * @generated
 */
public interface MuModel extends BaseModel<Mu>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Mgmt Unit model instance should use the {@link Mu} interface instead.
     */

    /**
     * Returns the primary key of this Mgmt Unit.
     *
     * @return the primary key of this Mgmt Unit
     */
    public MuPK getPrimaryKey();

    /**
     * Sets the primary key of this Mgmt Unit.
     *
     * @param primaryKey the primary key of this Mgmt Unit
     */
    public void setPrimaryKey(MuPK primaryKey);

    /**
     * Returns the hkey of this Mgmt Unit.
     *
     * @return the hkey of this Mgmt Unit
     */
    @AutoEscape
    public String getHkey();

    /**
     * Sets the hkey of this Mgmt Unit.
     *
     * @param hkey the hkey of this Mgmt Unit
     */
    public void setHkey(String hkey);

    /**
     * Returns the par of this Mgmt Unit.
     *
     * @return the par of this Mgmt Unit
     */
    @AutoEscape
    public String getPar();

    /**
     * Sets the par of this Mgmt Unit.
     *
     * @param par the par of this Mgmt Unit
     */
    public void setPar(String par);

    /**
     * Returns the title of this Mgmt Unit.
     *
     * @return the title of this Mgmt Unit
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this Mgmt Unit.
     *
     * @param title the title of this Mgmt Unit
     */
    public void setTitle(String title);

    /**
     * Returns the mu ID of this Mgmt Unit.
     *
     * @return the mu ID of this Mgmt Unit
     */
    public long getMuId();

    /**
     * Sets the mu ID of this Mgmt Unit.
     *
     * @param muId the mu ID of this Mgmt Unit
     */
    public void setMuId(long muId);

    /**
     * Returns the group ID of this Mgmt Unit.
     *
     * @return the group ID of this Mgmt Unit
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this Mgmt Unit.
     *
     * @param groupId the group ID of this Mgmt Unit
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this Mgmt Unit.
     *
     * @return the company ID of this Mgmt Unit
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this Mgmt Unit.
     *
     * @param companyId the company ID of this Mgmt Unit
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this Mgmt Unit.
     *
     * @return the user ID of this Mgmt Unit
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this Mgmt Unit.
     *
     * @param userId the user ID of this Mgmt Unit
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this Mgmt Unit.
     *
     * @return the user uuid of this Mgmt Unit
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this Mgmt Unit.
     *
     * @param userUuid the user uuid of this Mgmt Unit
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this Mgmt Unit.
     *
     * @return the user name of this Mgmt Unit
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this Mgmt Unit.
     *
     * @param userName the user name of this Mgmt Unit
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this Mgmt Unit.
     *
     * @return the create date of this Mgmt Unit
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this Mgmt Unit.
     *
     * @param createDate the create date of this Mgmt Unit
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this Mgmt Unit.
     *
     * @return the modified date of this Mgmt Unit
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this Mgmt Unit.
     *
     * @param modifiedDate the modified date of this Mgmt Unit
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.lycenway.chr.backbone.model.Mu mu);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.lycenway.chr.backbone.model.Mu> toCacheModel();

    @Override
    public com.lycenway.chr.backbone.model.Mu toEscapedModel();

    @Override
    public com.lycenway.chr.backbone.model.Mu toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
