package com.lycenway.chr.backbone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MuWufengXianlu service. Represents a row in the &quot;base_mu_wufeng_xianlu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lycenway.chr.backbone.model.impl.MuWufengXianluModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lycenway.chr.backbone.model.impl.MuWufengXianluImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuWufengXianlu
 * @see com.lycenway.chr.backbone.model.impl.MuWufengXianluImpl
 * @see com.lycenway.chr.backbone.model.impl.MuWufengXianluModelImpl
 * @generated
 */
public interface MuWufengXianluModel extends BaseModel<MuWufengXianlu>,
    GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Mgmt Unit of Wufeng Xianlu model instance should use the {@link MuWufengXianlu} interface instead.
     */

    /**
     * Returns the primary key of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the primary key of this Mgmt Unit of Wufeng Xianlu
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param primaryKey the primary key of this Mgmt Unit of Wufeng Xianlu
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the hkey of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the hkey of this Mgmt Unit of Wufeng Xianlu
     */
    @AutoEscape
    public String getHkey();

    /**
     * Sets the hkey of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param hkey the hkey of this Mgmt Unit of Wufeng Xianlu
     */
    public void setHkey(String hkey);

    /**
     * Returns the mu wufeng xianlu ID of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the mu wufeng xianlu ID of this Mgmt Unit of Wufeng Xianlu
     */
    public long getMuWufengXianluId();

    /**
     * Sets the mu wufeng xianlu ID of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param muWufengXianluId the mu wufeng xianlu ID of this Mgmt Unit of Wufeng Xianlu
     */
    public void setMuWufengXianluId(long muWufengXianluId);

    /**
     * Returns the group ID of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the group ID of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param groupId the group ID of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the company ID of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param companyId the company ID of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the user ID of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param userId the user ID of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the user uuid of this Mgmt Unit of Wufeng Xianlu
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param userUuid the user uuid of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the user name of this Mgmt Unit of Wufeng Xianlu
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param userName the user name of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the create date of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param createDate the create date of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this Mgmt Unit of Wufeng Xianlu.
     *
     * @return the modified date of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this Mgmt Unit of Wufeng Xianlu.
     *
     * @param modifiedDate the modified date of this Mgmt Unit of Wufeng Xianlu
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.lycenway.chr.backbone.model.MuWufengXianlu muWufengXianlu);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.lycenway.chr.backbone.model.MuWufengXianlu> toCacheModel();

    @Override
    public com.lycenway.chr.backbone.model.MuWufengXianlu toEscapedModel();

    @Override
    public com.lycenway.chr.backbone.model.MuWufengXianlu toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
