package com.lycenway.chr.backbone.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lycenway.chr.backbone.model.LOVMuType;
import com.lycenway.chr.backbone.service.LOVMuTypeLocalServiceUtil;

/**
 * The extended model base implementation for the LOVMuType service. Represents a row in the &quot;lov_mu_type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LOVMuTypeImpl}.
 * </p>
 *
 * @author lycenway
 * @see LOVMuTypeImpl
 * @see com.lycenway.chr.backbone.model.LOVMuType
 * @generated
 */
public abstract class LOVMuTypeBaseImpl extends LOVMuTypeModelImpl
    implements LOVMuType {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Lisf of Value Mgmt Unit Type model instance should use the {@link LOVMuType} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LOVMuTypeLocalServiceUtil.addLOVMuType(this);
        } else {
            LOVMuTypeLocalServiceUtil.updateLOVMuType(this);
        }
    }
}
