package com.lycenway.chr.backbone.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lycenway.chr.backbone.model.Mu;
import com.lycenway.chr.backbone.service.MuLocalServiceUtil;

/**
 * The extended model base implementation for the Mu service. Represents a row in the &quot;base_mu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MuImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuImpl
 * @see com.lycenway.chr.backbone.model.Mu
 * @generated
 */
public abstract class MuBaseImpl extends MuModelImpl implements Mu {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Mgmt Unit model instance should use the {@link Mu} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MuLocalServiceUtil.addMu(this);
        } else {
            MuLocalServiceUtil.updateMu(this);
        }
    }
}
