package com.lycenway.chr.backbone.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lycenway.chr.backbone.model.MuExt;
import com.lycenway.chr.backbone.service.MuExtLocalServiceUtil;

/**
 * The extended model base implementation for the MuExt service. Represents a row in the &quot;base_mu_ext&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MuExtImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuExtImpl
 * @see com.lycenway.chr.backbone.model.MuExt
 * @generated
 */
public abstract class MuExtBaseImpl extends MuExtModelImpl implements MuExt {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Mgmt Unit Extended Attributes model instance should use the {@link MuExt} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MuExtLocalServiceUtil.addMuExt(this);
        } else {
            MuExtLocalServiceUtil.updateMuExt(this);
        }
    }
}
