package com.lycenway.chr.backbone.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lycenway.chr.backbone.model.MuInterrel;
import com.lycenway.chr.backbone.service.MuInterrelLocalServiceUtil;

/**
 * The extended model base implementation for the MuInterrel service. Represents a row in the &quot;base_mu_interrel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MuInterrelImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuInterrelImpl
 * @see com.lycenway.chr.backbone.model.MuInterrel
 * @generated
 */
public abstract class MuInterrelBaseImpl extends MuInterrelModelImpl
    implements MuInterrel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Mgmt Unit Inter Relationship model instance should use the {@link MuInterrel} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MuInterrelLocalServiceUtil.addMuInterrel(this);
        } else {
            MuInterrelLocalServiceUtil.updateMuInterrel(this);
        }
    }
}
