package com.lycenway.chr.backbone.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.lycenway.chr.backbone.model.MuInterrel;
import com.lycenway.chr.backbone.model.MuInterrelModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the MuInterrel service. Represents a row in the &quot;base_mu_interrel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.lycenway.chr.backbone.model.MuInterrelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MuInterrelImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuInterrelImpl
 * @see com.lycenway.chr.backbone.model.MuInterrel
 * @see com.lycenway.chr.backbone.model.MuInterrelModel
 * @generated
 */
public class MuInterrelModelImpl extends BaseModelImpl<MuInterrel>
    implements MuInterrelModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Mgmt Unit Inter Relationship model instance should use the {@link com.lycenway.chr.backbone.model.MuInterrel} interface instead.
     */
    public static final String TABLE_NAME = "base_mu_interrel";
    public static final Object[][] TABLE_COLUMNS = {
            { "hkey", Types.VARCHAR },
            { "par", Types.VARCHAR },
            { "type_", Types.VARCHAR },
            { "muInterrelId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP }
        };
    public static final String TABLE_SQL_CREATE = "create table base_mu_interrel (hkey VARCHAR(75) null,par VARCHAR(75) null,type_ VARCHAR(75) null,muInterrelId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
    public static final String TABLE_SQL_DROP = "drop table base_mu_interrel";
    public static final String ORDER_BY_JPQL = " ORDER BY muInterrel.muInterrelId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY base_mu_interrel.muInterrelId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.lycenway.chr.backbone.model.MuInterrel"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.lycenway.chr.backbone.model.MuInterrel"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.lycenway.chr.backbone.model.MuInterrel"));
    private static ClassLoader _classLoader = MuInterrel.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            MuInterrel.class
        };
    private String _hkey;
    private String _par;
    private String _type;
    private long _muInterrelId;
    private long _groupId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private MuInterrel _escapedModel;

    public MuInterrelModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _muInterrelId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setMuInterrelId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _muInterrelId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return MuInterrel.class;
    }

    @Override
    public String getModelClassName() {
        return MuInterrel.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("hkey", getHkey());
        attributes.put("par", getPar());
        attributes.put("type", getType());
        attributes.put("muInterrelId", getMuInterrelId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String hkey = (String) attributes.get("hkey");

        if (hkey != null) {
            setHkey(hkey);
        }

        String par = (String) attributes.get("par");

        if (par != null) {
            setPar(par);
        }

        String type = (String) attributes.get("type");

        if (type != null) {
            setType(type);
        }

        Long muInterrelId = (Long) attributes.get("muInterrelId");

        if (muInterrelId != null) {
            setMuInterrelId(muInterrelId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }
    }

    @Override
    public String getHkey() {
        if (_hkey == null) {
            return StringPool.BLANK;
        } else {
            return _hkey;
        }
    }

    @Override
    public void setHkey(String hkey) {
        _hkey = hkey;
    }

    @Override
    public String getPar() {
        if (_par == null) {
            return StringPool.BLANK;
        } else {
            return _par;
        }
    }

    @Override
    public void setPar(String par) {
        _par = par;
    }

    @Override
    public String getType() {
        if (_type == null) {
            return StringPool.BLANK;
        } else {
            return _type;
        }
    }

    @Override
    public void setType(String type) {
        _type = type;
    }

    @Override
    public long getMuInterrelId() {
        return _muInterrelId;
    }

    @Override
    public void setMuInterrelId(long muInterrelId) {
        _muInterrelId = muInterrelId;
    }

    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            MuInterrel.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public MuInterrel toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (MuInterrel) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        MuInterrelImpl muInterrelImpl = new MuInterrelImpl();

        muInterrelImpl.setHkey(getHkey());
        muInterrelImpl.setPar(getPar());
        muInterrelImpl.setType(getType());
        muInterrelImpl.setMuInterrelId(getMuInterrelId());
        muInterrelImpl.setGroupId(getGroupId());
        muInterrelImpl.setCompanyId(getCompanyId());
        muInterrelImpl.setUserId(getUserId());
        muInterrelImpl.setUserName(getUserName());
        muInterrelImpl.setCreateDate(getCreateDate());
        muInterrelImpl.setModifiedDate(getModifiedDate());

        muInterrelImpl.resetOriginalValues();

        return muInterrelImpl;
    }

    @Override
    public int compareTo(MuInterrel muInterrel) {
        long primaryKey = muInterrel.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof MuInterrel)) {
            return false;
        }

        MuInterrel muInterrel = (MuInterrel) obj;

        long primaryKey = muInterrel.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<MuInterrel> toCacheModel() {
        MuInterrelCacheModel muInterrelCacheModel = new MuInterrelCacheModel();

        muInterrelCacheModel.hkey = getHkey();

        String hkey = muInterrelCacheModel.hkey;

        if ((hkey != null) && (hkey.length() == 0)) {
            muInterrelCacheModel.hkey = null;
        }

        muInterrelCacheModel.par = getPar();

        String par = muInterrelCacheModel.par;

        if ((par != null) && (par.length() == 0)) {
            muInterrelCacheModel.par = null;
        }

        muInterrelCacheModel.type = getType();

        String type = muInterrelCacheModel.type;

        if ((type != null) && (type.length() == 0)) {
            muInterrelCacheModel.type = null;
        }

        muInterrelCacheModel.muInterrelId = getMuInterrelId();

        muInterrelCacheModel.groupId = getGroupId();

        muInterrelCacheModel.companyId = getCompanyId();

        muInterrelCacheModel.userId = getUserId();

        muInterrelCacheModel.userName = getUserName();

        String userName = muInterrelCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            muInterrelCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            muInterrelCacheModel.createDate = createDate.getTime();
        } else {
            muInterrelCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            muInterrelCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            muInterrelCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        return muInterrelCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{hkey=");
        sb.append(getHkey());
        sb.append(", par=");
        sb.append(getPar());
        sb.append(", type=");
        sb.append(getType());
        sb.append(", muInterrelId=");
        sb.append(getMuInterrelId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("com.lycenway.chr.backbone.model.MuInterrel");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>hkey</column-name><column-value><![CDATA[");
        sb.append(getHkey());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>par</column-name><column-value><![CDATA[");
        sb.append(getPar());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>type</column-name><column-value><![CDATA[");
        sb.append(getType());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>muInterrelId</column-name><column-value><![CDATA[");
        sb.append(getMuInterrelId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
