package com.lycenway.chr.backbone.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import com.lycenway.chr.backbone.model.Mu;
import com.lycenway.chr.backbone.model.MuModel;
import com.lycenway.chr.backbone.service.persistence.MuPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Mu service. Represents a row in the &quot;base_mu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.lycenway.chr.backbone.model.MuModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MuImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuImpl
 * @see com.lycenway.chr.backbone.model.Mu
 * @see com.lycenway.chr.backbone.model.MuModel
 * @generated
 */
public class MuModelImpl extends BaseModelImpl<Mu> implements MuModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Mgmt Unit model instance should use the {@link com.lycenway.chr.backbone.model.Mu} interface instead.
     */
    public static final String TABLE_NAME = "base_mu";
    public static final Object[][] TABLE_COLUMNS = {
            { "hkey", Types.VARCHAR },
            { "par", Types.VARCHAR },
            { "title", Types.VARCHAR },
            { "muId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP }
        };
    public static final String TABLE_SQL_CREATE = "create table base_mu (hkey VARCHAR(75) not null,par VARCHAR(75) null,title VARCHAR(75) null,muId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,primary key (hkey, muId))";
    public static final String TABLE_SQL_DROP = "drop table base_mu";
    public static final String ORDER_BY_JPQL = " ORDER BY mu.id.hkey ASC, mu.id.muId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY base_mu.hkey ASC, base_mu.muId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.lycenway.chr.backbone.model.Mu"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.lycenway.chr.backbone.model.Mu"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.lycenway.chr.backbone.model.Mu"));
    private static ClassLoader _classLoader = Mu.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Mu.class };
    private String _hkey;
    private String _par;
    private String _title;
    private long _muId;
    private long _groupId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private Mu _escapedModel;

    public MuModelImpl() {
    }

    @Override
    public MuPK getPrimaryKey() {
        return new MuPK(_hkey, _muId);
    }

    @Override
    public void setPrimaryKey(MuPK primaryKey) {
        setHkey(primaryKey.hkey);
        setMuId(primaryKey.muId);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return new MuPK(_hkey, _muId);
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((MuPK) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return Mu.class;
    }

    @Override
    public String getModelClassName() {
        return Mu.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("hkey", getHkey());
        attributes.put("par", getPar());
        attributes.put("title", getTitle());
        attributes.put("muId", getMuId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String hkey = (String) attributes.get("hkey");

        if (hkey != null) {
            setHkey(hkey);
        }

        String par = (String) attributes.get("par");

        if (par != null) {
            setPar(par);
        }

        String title = (String) attributes.get("title");

        if (title != null) {
            setTitle(title);
        }

        Long muId = (Long) attributes.get("muId");

        if (muId != null) {
            setMuId(muId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }
    }

    @Override
    public String getHkey() {
        if (_hkey == null) {
            return StringPool.BLANK;
        } else {
            return _hkey;
        }
    }

    @Override
    public void setHkey(String hkey) {
        _hkey = hkey;
    }

    @Override
    public String getPar() {
        if (_par == null) {
            return StringPool.BLANK;
        } else {
            return _par;
        }
    }

    @Override
    public void setPar(String par) {
        _par = par;
    }

    @Override
    public String getTitle() {
        if (_title == null) {
            return StringPool.BLANK;
        } else {
            return _title;
        }
    }

    @Override
    public void setTitle(String title) {
        _title = title;
    }

    @Override
    public long getMuId() {
        return _muId;
    }

    @Override
    public void setMuId(long muId) {
        _muId = muId;
    }

    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @Override
    public Mu toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Mu) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        MuImpl muImpl = new MuImpl();

        muImpl.setHkey(getHkey());
        muImpl.setPar(getPar());
        muImpl.setTitle(getTitle());
        muImpl.setMuId(getMuId());
        muImpl.setGroupId(getGroupId());
        muImpl.setCompanyId(getCompanyId());
        muImpl.setUserId(getUserId());
        muImpl.setUserName(getUserName());
        muImpl.setCreateDate(getCreateDate());
        muImpl.setModifiedDate(getModifiedDate());

        muImpl.resetOriginalValues();

        return muImpl;
    }

    @Override
    public int compareTo(Mu mu) {
        MuPK primaryKey = mu.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Mu)) {
            return false;
        }

        Mu mu = (Mu) obj;

        MuPK primaryKey = mu.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Mu> toCacheModel() {
        MuCacheModel muCacheModel = new MuCacheModel();

        muCacheModel.hkey = getHkey();

        String hkey = muCacheModel.hkey;

        if ((hkey != null) && (hkey.length() == 0)) {
            muCacheModel.hkey = null;
        }

        muCacheModel.par = getPar();

        String par = muCacheModel.par;

        if ((par != null) && (par.length() == 0)) {
            muCacheModel.par = null;
        }

        muCacheModel.title = getTitle();

        String title = muCacheModel.title;

        if ((title != null) && (title.length() == 0)) {
            muCacheModel.title = null;
        }

        muCacheModel.muId = getMuId();

        muCacheModel.groupId = getGroupId();

        muCacheModel.companyId = getCompanyId();

        muCacheModel.userId = getUserId();

        muCacheModel.userName = getUserName();

        String userName = muCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            muCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            muCacheModel.createDate = createDate.getTime();
        } else {
            muCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            muCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            muCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        return muCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{hkey=");
        sb.append(getHkey());
        sb.append(", par=");
        sb.append(getPar());
        sb.append(", title=");
        sb.append(getTitle());
        sb.append(", muId=");
        sb.append(getMuId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("com.lycenway.chr.backbone.model.Mu");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>hkey</column-name><column-value><![CDATA[");
        sb.append(getHkey());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>par</column-name><column-value><![CDATA[");
        sb.append(getPar());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>title</column-name><column-value><![CDATA[");
        sb.append(getTitle());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>muId</column-name><column-value><![CDATA[");
        sb.append(getMuId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
