package com.lycenway.chr.backbone.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lycenway.chr.backbone.model.MuQuxianQujian;
import com.lycenway.chr.backbone.service.MuQuxianQujianLocalServiceUtil;

/**
 * The extended model base implementation for the MuQuxianQujian service. Represents a row in the &quot;base_mu_quxian_qujian&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MuQuxianQujianImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuQuxianQujianImpl
 * @see com.lycenway.chr.backbone.model.MuQuxianQujian
 * @generated
 */
public abstract class MuQuxianQujianBaseImpl extends MuQuxianQujianModelImpl
    implements MuQuxianQujian {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Mgmt Unit of Quxian Qujian model instance should use the {@link MuQuxianQujian} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MuQuxianQujianLocalServiceUtil.addMuQuxianQujian(this);
        } else {
            MuQuxianQujianLocalServiceUtil.updateMuQuxianQujian(this);
        }
    }
}
