package com.lycenway.chr.backbone.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lycenway.chr.backbone.model.MuWufengXianlu;
import com.lycenway.chr.backbone.service.MuWufengXianluLocalServiceUtil;

/**
 * The extended model base implementation for the MuWufengXianlu service. Represents a row in the &quot;base_mu_wufeng_xianlu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MuWufengXianluImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuWufengXianluImpl
 * @see com.lycenway.chr.backbone.model.MuWufengXianlu
 * @generated
 */
public abstract class MuWufengXianluBaseImpl extends MuWufengXianluModelImpl
    implements MuWufengXianlu {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Mgmt Unit of Wufeng Xianlu model instance should use the {@link MuWufengXianlu} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MuWufengXianluLocalServiceUtil.addMuWufengXianlu(this);
        } else {
            MuWufengXianluLocalServiceUtil.updateMuWufengXianlu(this);
        }
    }
}
