package com.lycenway.chr.backbone.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lycenway.chr.backbone.model.MuZhengxianPodao;
import com.lycenway.chr.backbone.service.MuZhengxianPodaoLocalServiceUtil;

/**
 * The extended model base implementation for the MuZhengxianPodao service. Represents a row in the &quot;base_mu_zhengxian_podao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MuZhengxianPodaoImpl}.
 * </p>
 *
 * @author lycenway
 * @see MuZhengxianPodaoImpl
 * @see com.lycenway.chr.backbone.model.MuZhengxianPodao
 * @generated
 */
public abstract class MuZhengxianPodaoBaseImpl extends MuZhengxianPodaoModelImpl
    implements MuZhengxianPodao {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Mgmt Unit of Zhengxian Podao model instance should use the {@link MuZhengxianPodao} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MuZhengxianPodaoLocalServiceUtil.addMuZhengxianPodao(this);
        } else {
            MuZhengxianPodaoLocalServiceUtil.updateMuZhengxianPodao(this);
        }
    }
}
